
{
🌟 DESAFIO DE PROGRAMAÇÃO - FUNDAMENTOS 💻
------------------------------------------
📅 Data de criação: 10/12/2025
✍️ Autora: Anna Karolynna Mota 
🏫 Instituto Federal Fluminense - Campus Itaperuna
🎯 Linguagem: Portugol

🧩  Enunciado: Crie um algoritmo que armazene em um vetor NOME e imprima uma listagem numerada. 

}
Algoritmo "semnome"

Var
   nomes: vetor[1..10] de caracter
   i: inteiro


Inicio
   para i de 1 ate 10 faca
      escreva("Informe um nome: ")
      leia(nomes[i])
   fimpara
   
   para i de 1 ate 10 faca
   escreval("[",i,"]: ", nomes[i])
   fimpara


Fimalgoritmo

